export const talentInsightsFields = {
  "Finance And Accounting": {
    subSkills: {
      "Financial Planning And Analysis": [
        "Financial Analyst",
        "Budget Analyst",
        "Financial Planning Manager",
        "Corporate Strategist",
        "Risk Management Analyst",
      ],
      Accounting: [
        "Staff Accountant",
        "Senior Accountant",
        "Payroll Specialist",
        "Tax Accountant",
        "Accounts Payable/Receivable Specialist",
        "Audit Manager",
        "Forensic Accountant",
      ],
      "Treasury And Corporate Finance": [
        "Treasurer",
        "Treasury Analyst",
        "Corporate Finance Manager",
        "Mergers and Acquisitions (M&A) Analyst",
        "Investment Analyst",
      ],
      "Internal Audit": [
        "Internal Auditor",
        "Compliance Auditor",
        "IT Auditor",
        "Operational Auditor",
        "Audit Director",
      ],
      "Tax And Compliance": [
        "Tax Manager",
        "Tax Specialist",
        "Compliance Officer",
        "Regulatory Affairs Specialist",
        "Legal Compliance Manager",
      ],
    },
  },
  "Human Resources": {
    subSkills: {
      "Talent Acquisition": [
        "Recruiter",
        "Recruitment Manager",
        "Talent Acquisition Specialist",
        "Headhunter",
        "Recruitment Coordinator",
      ],
      "Employee Relations And Engagement": [
        "Employee Relations Manager",
        "HR Business Partner",
        "Employee Engagement Specialist",
        "Diversity and Inclusion Officer",
        "Labor Relations Specialist",
      ],
      "Learning And Development": [
        "Learning and Development Manager",
        "Training Coordinator",
        "E-Learning Specialist",
        "Leadership Development Coach",
        "Instructional Designer",
      ],
      "Compensation And Benefits": [
        "Compensation Analyst",
        "Benefits Coordinator",
        "Payroll Manager",
        "Compensation and Benefits Manager",
        "Total Rewards Specialist",
      ],
      "HR Operations": [
        "HR Generalist",
        "HR Operations Manager",
        "HRIS Analyst",
        "HR Coordinator",
        "HR Data Analyst",
      ],
    },
  },
  "Marketing And Communications": {
    subSkills: {
      "Marketing Strategy And Planning": [
        "Marketing Manager",
        "Brand Manager",
        "Product Marketing Manager",
        "Market Research Analyst",
        "Growth Marketing Specialist",
      ],
      "Digital Marketing": [
        "Digital Marketing Specialist",
        "SEO/SEM Specialist",
        "Social Media Manager",
        "Content Marketing Manager",
        "Email Marketing Specialist",
      ],
      "Corporate Communications": [
        "Corporate Communications Manager",
        "Public Relations Specialist",
        "Internal Communications Manager",
        "Media Relations Manager",
        "Copywriter",
      ],
      "Creative Services": [
        "Graphic Designer",
        "Creative Director",
        "Multimedia Designer",
        "Video Content Producer",
        "UX/UI Designer",
      ],
      "Event Management": [
        "Event Coordinator",
        "Event Marketing Manager",
        "Trade Show Specialist",
        "Corporate Events Planner",
        "Sponsorship Manager",
      ],
    },
  },
  "Sales And Business Development": {
    subSkills: {
      "Sales Management": [
        "Sales Manager",
        "Regional Sales Manager",
        "Account Manager",
        "Sales Director",
        "Territory Sales Manager",
      ],
      "Business Development": [
        "Business Development Manager",
        "Partnership Manager",
        "Sales Development Representative",
        "Proposal Manager",
        "Channel Sales Manager",
      ],
      "Customer Relationship Management": [
        "CRM Specialist",
        "Key Account Manager",
        "Client Success Manager",
        "Relationship Manager",
        "Customer Service Manager",
      ],
      "Inside Sales": [
        "Inside Sales Representative",
        "Sales Coordinator",
        "Lead Generation Specialist",
        "Sales Support Specialist",
        "Sales Operations Analyst",
      ],
      "Sales Enablement": [
        "Sales Trainer",
        "Sales Operations Manager",
        "Sales Enablement Specialist",
        "Proposal Writer",
        "Sales Content Developer",
      ],
    },
  },
  "Operations And SupplyChain": {
    subSkills: {
      "Operations Management": [
        "Operations Manager",
        "Operations Analyst",
        "Director of Operations",
        "Business Process Manager",
        "Continuous Improvement Manager",
      ],
      "Supply Chain Management": [
        "Supply Chain Manager",
        "Procurement Specialist",
        "Inventory Control Manager",
        "Logistics Coordinator",
        "Demand Planner",
      ],
      "Manufacturing And Production": [
        "Production Manager",
        "Quality Assurance Specialist",
        "Plant Manager",
        "Production Planner",
        "Manufacturing Engineer",
      ],
      "Facilities Management": [
        "Facilities Manager",
        "Maintenance Supervisor",
        "Facilities Coordinator",
        "Health and Safety Officer",
        "Environmental Compliance Specialist",
      ],
      "Procurement And Sourcing": [
        "Procurement Manager",
        "Sourcing Specialist",
        "Vendor Management Specialist",
        "Contract Manager",
        "Purchasing Coordinator",
      ],
    },
  },
};

export const talentInsightsGeographies = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
