export const industryTrendsFields = {
  "Primary Industries": [
    "Agriculture",
    "Mining",
    "Forestry",
    "Fishing",
    "Oil and Gas Extraction",
  ],
  "Manufacturing Industries": [
    "Automotive",
    "Aerospace",
    "Pharmaceuticals",
    "Textiles",
    "Electronics",
    "Food and Beverage",
    "Chemical Manufacturing",
    "Furniture and Home Goods",
    "Industrial Machinery",
    "Consumer Goods",
  ],
  "Service Industries": [
    "Healthcare",
    "Education",
    "Hospitality and Tourism",
    "Retail",
    "Financial Services",
    "Insurance",
    "Real Estate",
    "Professional Services (Consulting, Legal, Accounting)",
    "Telecommunications",
    "Media and Entertainment",
  ],
  "Technology Industries": [
    "Information Technology (IT)",
    "Software Development",
    "Artificial Intelligence and Machine Learning",
    "Cybersecurity",
    "Cloud Computing",
    "E-commerce",
    "Semiconductors",
    "Biotechnology",
    "Gaming and Virtual Reality",
    "Fintech",
  ],
  "Transportation and Logistics Industries": [
    "Residential Construction",
    "Commercial Construction",
    "Civil Engineering",
    "Infrastructure Development",
    "Urban Planning",
    "Real Estate Development",
    "Architecture",
  ],
  "Energy Utilities Industries": [
    "Renewable Energy (Solar, Wind, Hydropower)",
    "Nuclear Energy",
    "Utilities (Electricity, Water, Gas)",
    "Oil and Gas",
    "Coal Industry",
    "Waste Management",
    "Environmental Services",
  ],
  "Financial and Investment Industries": [
    "Banking",
    "Investment Management",
    "Private Equity",
    "Venture Capital",
    "Hedge Funds",
    "Insurance",
    "Credit Unions",
  ],
  "Consumer and Retail Industries": [
    "Luxury Goods",
    "Fashion and Apparel",
    "E-commerce",
    "Grocery and Supermarkets",
    "Home Improvement",
    "Automotive Retail",
    "Consumer Electronics",
  ],
  "Public and Governmental Industries": [
    "Public Administration",
    "Defense and Military",
    "Law Enforcement",
    "Public Health",
    "Social Services",
    "Education (Public Sector)",
    "Transportation (Public Sector)",
  ],
  "Non-Profit and Social Impacts Industries": [
    "Non-Governmental Organizations (NGOs)",
    "Charities",
    "Social Enterprises",
    "Foundations",
    "Environmental Advocacy",
    "Human Rights Organizations",
    "International Aid",
  ],
  "Research and Development Industries": [
    "Scientific Research",
    "R&D in Technology",
    "Pharmaceutical Research",
    "Agricultural Research",
    "Environmental Research",
  ],
  "Arts and Culture Industries": [
    "Fine Arts",
    "Performing Arts",
    "Museums and Galleries",
    "Publishing",
    "Music Industry",
    "Film and Television",
    "Cultural Heritage Preservation",
  ],
};
